#!/bin/sh

##
# Just do some sanity check before start Radiorec
#
cd src

PYTHON=`which python`

if [ -z "$PYTHON" ]; then
	echo
	echo "Python was not found."
	echo "Radiorec will not execute. Please, install Python first."
	echo
fi

$PYTHON << EOF
import sys

try:
	import gi
	gi.require_version("Gtk", "3.0")
	gi.require_version("Gdk", "3.0")
	gi.require_version("GdkPixbuf", "2.0")
	from gi.repository import GObject, GdkPixbuf, Gdk, Gtk
except:
	print 'PyGTK3 package was not found.'
	print 'Radiorec will not execute. Please, install PyGTK3 first.'
	sys.exit(1)

try:
	import gi
	gi.require_version('Gst', '1.0')
	from gi.repository import GObject, Gst
except:
	dia = Gtk.Dialog("Error", None,
						Gtk.DialogFlags.MODAL | Gtk.DialogFlags.DESTROY_WITH_PARENT,
						(Gtk.STOCK_OK, Gtk.ResponseType.OK))
	wicon = Gtk.Image.new_from_stock(Gtk.STOCK_DIALOG_ERROR, Gtk.IconSize.DIALOG)
	txt   = Gtk.Label("PyGst (>=1.0) package was not found.\nRadiorec will not execute. Please, install PyGst (>=1.0) first.")
	txt.set_line_wrap(True)
	hbox  = Gtk.HBox()
	hbox.pack_start(wicon, True, True, 0)
	hbox.pack_start(txt, True, True, 0)
	dia.vbox.pack_start(hbox, True, True, 0)
	picon = dia.render_icon(Gtk.STOCK_DIALOG_ERROR, Gtk.IconSize.MENU)
	dia.set_icon(picon)
	dia.show_all()
	dia.run()
	dia.destroy()
	sys.exit(1)

sys.exit(0)
EOF

[ $? -eq 0 ] && ./radiorec.py

